/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.app;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.DriverManager;

/**
 *
 * @author admin
 */
public class DANGNHAP extends javax.swing.JFrame {

    /**
     * Creates new form DANGNHAP
     */
    public DANGNHAP() {
        initComponents();
    }
    String driver ="com.mysql.cj.jdbc.Driver";
    String url="jdbc:mysql://localhost/csdlapp";
    String user="root";
    String password="";
    Statement st;
    ResultSet rs;
    public static String ACCOUNTNAME = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTENTK = new javax.swing.JTextField();
        btnDANGNHAP = new javax.swing.JButton();
        btnDANGKY = new javax.swing.JButton();
        txtMATKHAU = new javax.swing.JPasswordField();
        HIENMATKHAU = new javax.swing.JCheckBox();
        chkNHOTOI = new javax.swing.JCheckBox();
        btnRESET = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Account name");

        jLabel4.setText("Password");

        txtTENTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTENTKActionPerformed(evt);
            }
        });

        btnDANGNHAP.setText("Đăng nhập");
        btnDANGNHAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDANGNHAPActionPerformed(evt);
            }
        });

        btnDANGKY.setText("Bạn chưa có tài khoản?");
        btnDANGKY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDANGKYActionPerformed(evt);
            }
        });

        HIENMATKHAU.setText("Hiện mật khẩu");
        HIENMATKHAU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HIENMATKHAUActionPerformed(evt);
            }
        });

        chkNHOTOI.setText("Remember?");
        chkNHOTOI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNHOTOIActionPerformed(evt);
            }
        });

        btnRESET.setText("RESET");
        btnRESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRESETActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMATKHAU, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(btnDANGKY, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(8, 8, 8)
                                .addComponent(HIENMATKHAU))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chkNHOTOI, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRESET))
                            .addComponent(txtTENTK, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(btnDANGNHAP)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtTENTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMATKHAU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(HIENMATKHAU)))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkNHOTOI)
                    .addComponent(btnRESET, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDANGNHAP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(btnDANGKY)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTENTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTENTKActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTENTKActionPerformed

    private void btnDANGNHAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDANGNHAPActionPerformed
            // TODO add your handling code here:
            ACCOUNTNAME = txtTENTK.getText();
            
        try{  
            //chua code dang nhap
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection(url,user,password );
            String sql = "SELECT * FROM users Where ACCOUNTNAME = ? and PASSWORD = ? ";
            PreparedStatement ps = con.prepareCall(sql);
            ps.setString(1,txtTENTK.getText());
            ps.setString(2,txtMATKHAU.getText());
            rs=ps.executeQuery();
            
            if(txtTENTK.getText().equals("")||txtMATKHAU.getText().equals("")){
                JOptionPane.showMessageDialog(this,"KHONG DUOC DE TRONG THONG TIN");
            }
            else if(rs.next()){
                new HOME().setVisible(true);
                dispose();
                
            }else {
                JOptionPane.showMessageDialog(this, "Tai khoan hoac mat khau sai");
            }

        } catch (Exception ex) {
            
        }
        
        
        
    }//GEN-LAST:event_btnDANGNHAPActionPerformed

    private void HIENMATKHAUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HIENMATKHAUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HIENMATKHAUActionPerformed

    private void btnRESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRESETActionPerformed
        // TODO add your handling code here:
        txtTENTK.setText("");
        txtMATKHAU.setText("");
        
        
    }//GEN-LAST:event_btnRESETActionPerformed

    private void btnDANGKYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDANGKYActionPerformed
        // TODO add your handling code here:
        //CODE CHUYEN GIAO DIEN KHI NHAN NUT
        new DANGKY().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDANGKYActionPerformed

    private void chkNHOTOIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNHOTOIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkNHOTOIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DANGNHAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DANGNHAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DANGNHAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DANGNHAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DANGNHAP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox HIENMATKHAU;
    private javax.swing.JButton btnDANGKY;
    private javax.swing.JButton btnDANGNHAP;
    private javax.swing.JButton btnRESET;
    private javax.swing.JCheckBox chkNHOTOI;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtMATKHAU;
    private javax.swing.JTextField txtTENTK;
    // End of variables declaration//GEN-END:variables
}
