/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.app;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.DriverManager;
/**
 *
 * @author admin
 */
public class THONGTINCANHAN extends javax.swing.JFrame {
    String accountname = DANGNHAP.ACCOUNTNAME;
    
    String ma_so;
    
    Statement st;
    ResultSet rs;
    ResultSet rs1;
    ResultSet rs3;
    ResultSet rs6;
    /**
     * Creates new form THONGTINCANHAN
     */
    public THONGTINCANHAN() {
        initComponents();
        
        try {
            Connection con = KETNOI.dbConnector();
            String sql = "SELECT * FROM users Where ACCOUNTNAME = ? ";
            PreparedStatement ps = con.prepareCall(sql);
            ps.setString(1,accountname);
            rs=ps.executeQuery();
            if(rs.next()){
                System.out.println("TIM DU LIEU THANH CONG");
            }
            
            ma_so=rs.getString(1);
           
            System.out.print(ma_so);
            String sql1="SELECT * FROM tt_ca_nhan WHERE MA_THANHVIEN=?";
            PreparedStatement ps1 = con.prepareCall(sql1);
            ps1.setString(1, ma_so);
            rs1=ps1.executeQuery();
            
            if(rs1.next()){
                txtMA.setText(rs1.getString(2));
                txtUSERNAME.setText(rs1.getString(3));
            }
            String sql3="SELECT * FROM tt_ca_nhan WHERE MA_THANHVIEN=?";
            PreparedStatement ps3 = con.prepareCall(sql3);
            ps3.setString(1, ma_so);
            rs3=ps3.executeQuery();
            
            if(rs3.next()){
                int gt1=rs3.getInt(4);
                txtCHIEUCAO.setText(rs3.getString(5));
                txtCANNANG.setText(rs3.getString(6));
                txtKCAL_COTHE.setText(rs3.getString(7));
                txtKCAL_TAPLUYEN.setText(rs3.getString(8));
                txtKCAL_NAPVAO.setText(rs3.getString(9));
                int trangthai=rs3.getInt(10);
                if (gt1==1) {
                    btnGT_NAM.setSelected(true);
                    btnGT_NU.setSelected(false);
                } else {
                    btnGT_NAM.setSelected(false);
                    btnGT_NU.setSelected(true);
                }
                if(trangthai==1){
                    txtTT.setText("Dư thừa Kcal");
                }else{
                    txtTT.setText("Thiếu  Kcal");
                }
            }else{
                JOptionPane.showMessageDialog(this, "CHUA CO DU LIEU DE HIEN THI");
            }

        } catch (Exception e) {
        }
        
        // test xem co lay duoc du lieu ko
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnBACK = new javax.swing.JButton();
        txtMA = new javax.swing.JTextField();
        txtUSERNAME = new javax.swing.JTextField();
        btnGT_NAM = new javax.swing.JRadioButton();
        btnGT_NU = new javax.swing.JRadioButton();
        txtCHIEUCAO = new javax.swing.JTextField();
        txtCANNANG = new javax.swing.JTextField();
        txtKCAL_COTHE = new javax.swing.JTextField();
        txtKCAL_TAPLUYEN = new javax.swing.JTextField();
        txtKCAL_NAPVAO = new javax.swing.JTextField();
        btnINSERT = new javax.swing.JButton();
        txtTT = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Thông tin cá nhân của bạn ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tên người dùng");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Giới tính");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Chiều cao");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Cân nặng");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Lượng Kcal cơ thể tiêu thụ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Kcal tập luyện");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Kcal nạp vào");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Trạng thái");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Mã thành viên");

        btnBACK.setText("BACK");
        btnBACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBACKActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnGT_NAM);
        btnGT_NAM.setText("Nam");
        btnGT_NAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGT_NAMActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnGT_NU);
        btnGT_NU.setText("Nữ");
        btnGT_NU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGT_NUActionPerformed(evt);
            }
        });

        btnINSERT.setText("Cập nhật");
        btnINSERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnINSERTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBACK)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnINSERT)
                                        .addGap(154, 154, 154))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(112, 112, 112)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTT, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtKCAL_NAPVAO, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel3))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnGT_NAM)
                                        .addGap(31, 31, 31)
                                        .addComponent(btnGT_NU))
                                    .addComponent(txtKCAL_TAPLUYEN)
                                    .addComponent(txtKCAL_COTHE)
                                    .addComponent(txtCANNANG)
                                    .addComponent(txtCHIEUCAO)
                                    .addComponent(txtMA)
                                    .addComponent(txtUSERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUSERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGT_NAM, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGT_NU)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCHIEUCAO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addComponent(txtCANNANG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtKCAL_COTHE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtKCAL_TAPLUYEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtKCAL_NAPVAO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBACK)
                    .addComponent(btnINSERT))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBACKActionPerformed
        // TODO add your handling code here:
        new HOME().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBACKActionPerformed

    private void btnGT_NAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGT_NAMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGT_NAMActionPerformed

    private void btnGT_NUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGT_NUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGT_NUActionPerformed

    private void btnINSERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnINSERTActionPerformed
        // TODO add your handling code here:
        try {
            System.out.print(ma_so);
            Connection conn = KETNOI.dbConnector();
            int gt = 1;
            if(btnGT_NU.isSelected()){
                gt = 0;
            }
            
            String cothe= txtKCAL_COTHE.getText();
            int cothe1 = Integer.parseInt(cothe);
            String vao= txtKCAL_NAPVAO.getText();
            int vao1 = Integer.parseInt(vao);
            String ra= txtKCAL_TAPLUYEN.getText();
            int ra1 = Integer.parseInt(ra);
            int trangthai;
            if(ra1 + cothe1 > vao1 ){
                trangthai = 0;
            }else{
                trangthai =1;
            }
            
            String sql = "UPDATE tt_ca_nhan SET GT=?, CHIEUCAO=?, CANNANG=?, KCAL_COTHETT=?,KCAL_TAPLUYEN=?,KCAL_NAP_VAO=?, TRANGTHAI=? WHERE MA_THANHVIEN=?";
 
            PreparedStatement statement = conn.prepareStatement(sql);
            statement.setInt(1, gt);
            statement.setString(2, txtCHIEUCAO.getText());
            statement.setString(3, txtCANNANG.getText());
            statement.setString(4, txtKCAL_COTHE.getText());
            statement.setString(5, txtKCAL_TAPLUYEN.getText());
            statement.setString(6, txtKCAL_NAPVAO.getText());
            statement.setInt(7, trangthai);
            statement.setString(8, ma_so);
 
            int rowsUpdated = statement.executeUpdate();
            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(this,"THEM DU LIEU THANH CONG ");
                
            }
            
            String sql6="SELECT * FROM tt_ca_nhan WHERE MA_THANHVIEN=?";
            PreparedStatement ps6 = conn.prepareCall(sql6);
            ps6.setString(1, ma_so);
            rs6=ps6.executeQuery();
            
            if(rs6.next()){
                System.out.print("da load lai");
                int gt2=rs6.getInt(4);
                txtCHIEUCAO.setText(rs6.getString(5));
                txtCANNANG.setText(rs6.getString(6));
                txtKCAL_COTHE.setText(rs6.getString(7));
                txtKCAL_TAPLUYEN.setText(rs6.getString(8));
                txtKCAL_NAPVAO.setText(rs6.getString(9));
                int trangthai2=rs6.getInt(10);
                
                System.out.print("gt la:"+gt2);
                System.out.print("gia tri la:"+trangthai2);
                if (gt2==1) {
                    btnGT_NAM.setSelected(true);
                    btnGT_NU.setSelected(false);
                } else {
                    btnGT_NAM.setSelected(false);
                    btnGT_NU.setSelected(true);
                }
                if(trangthai2==1){
                    txtTT.setText("Dư thừa Kcal");
                }else{
                    txtTT.setText("Thiếu  Kcal");
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnINSERTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(THONGTINCANHAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(THONGTINCANHAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(THONGTINCANHAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(THONGTINCANHAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new THONGTINCANHAN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBACK;
    private javax.swing.JRadioButton btnGT_NAM;
    private javax.swing.JRadioButton btnGT_NU;
    private javax.swing.JButton btnINSERT;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCANNANG;
    private javax.swing.JTextField txtCHIEUCAO;
    private javax.swing.JTextField txtKCAL_COTHE;
    private javax.swing.JTextField txtKCAL_NAPVAO;
    private javax.swing.JTextField txtKCAL_TAPLUYEN;
    private javax.swing.JTextField txtMA;
    private javax.swing.JTextField txtTT;
    private javax.swing.JTextField txtUSERNAME;
    // End of variables declaration//GEN-END:variables
}
